# Basic
title: 雷园的博客
subtitle: 让我们在这里好好交流一些技术上的信息
welcome_message: 这里是雷园的博客
description: 既然选择了技术，那也就是选择了无尽的学习
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 查看博客

# Navigation buttons in the front page.
nav:
    - {title: 头条主页, description: 我的今日头条主页, url: 'https://www.toutiao.com/c/user/6132192948/#mid=1616456407686158'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    github: leiyuanblog
    twitter: leiyuan
    mail: 15326047083@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
